### PR TITLE
Update web-sites-deploy.md

### PR DESCRIPTION
**Pull request by CarstenK-MSFT**
Changed Gewusst-wie-Anleitungen to "Gewusst wie"-Anleitungen to provide a consistent format as on other Microsoft sites.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CarstenK-MSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by v-chalke** [comment]
Hi CarstenK-MSFT,

Thank you for your feedback and suggestion! I reviewed it but could not find a relevant inconsistency compared to other pages, so it does not meet our acceptance criteria. Therefore, I am closing this PR right now. Please feel free to open a new PR.

Microsoft C&E Localization Team

**Comment by CarstenK-MSFT** [comment]
A search on Microsoft.de for example shows this is not consistent with how it's used on other MS sites.

**Comment by v-chalke** [comment]
Hi CarstenK-MSFT,

Thank you for your feedback and suggestion! Performing searches on Bing and Google shows that both Gewusst-wie-Anleitung(en) and "Gewusst-wie"-Anleitung(en) occur very rarely. Actually, I could only find a single instance of "Gewusst-wie"-Anleitung (with the quotes). In addition, from a linguistic perspective, I'd prefer Gewusst-wie-Anleitung for stylistic reasons.

Maybe you could provide some figures or links that support your view that "Gewusst-wie"-Anleitung is the preferred translation? From my side, I cannot second this but I am open for substantiation.

Microsoft C&E Localization Team

**Comment by azurecla** [comment]
Hi __@CarstenK-MSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request closed without merging**
